export const ERROR_CODES = {
  CLIENT_NOT_FOUND: "CLIENT_NOT_FOUND",
  SYNC_FAILED: "SYNC_FAILED",
  INVALID_DATE_RANGE: "INVALID_DATE_RANGE",
  NO_ADS: "NO_ADS",
  NO_TOKEN: "NO_TOKEN",
  NO_REFRESH_TOKEN: "NO_REFRESH_TOKEN",
  OAUTH_NOT_CONFIGURED: "OAUTH_NOT_CONFIGURED",
  SYNC_NOT_CONFIGURED: "SYNC_NOT_CONFIGURED",
  PLATFORM_SYNC_FAILED: "PLATFORM_SYNC_FAILED",
};
